### ISSUE TITLE
Sanitize HTML in release body

### ISSUE THREAD

**Issue by zeke** [electron/releases#17]
Example: https://github.com/electron/electronjs.org/issues/1296

`Fixed issue allowing bundles to be selected in <input file="type"> open file dialog.` should not display an input!

The [dompurify](https://ghub.io/dompurify) module might be a good option for this.

**Comment by ikkisoft** [comment]
Use a whitelist of allowed tags 👍

**Comment by zeke** [comment]
In the case of `Fixed issue allowing bundles to be selected in <input file="type"> open file dialog.`, we don't actually want to strip out the `<input>` content, it should just be encoded to `&lt;input&gt;`. Perhaps this can be solved with a remark plugin in the [hubdown](https://ghub.io/hubdown) module.
