### ISSUE TITLE
Past few 19.beta releases are missing

### ISSUE THREAD

**Issue by baparham** [electron/releases#171]
It seems that the beta channel releases have stopped updating after 19.0.0-beta.4, missing betas 5-7.

Is this expected to happen until some other event triggers a sync of the data?

**Comment by baparham** [comment]
Oh, I see, the latest actions have been failing, so they probably aren't updating the data back into the library.

https://github.com/electron/releases/runs/6483830096?check_suite_focus=true

What help do you need to fix this issue?

**Comment by baparham** [comment]
`v20.0.0-nightly.20220516` seems to be missing the `deps` property, which is making the tests fail. I am not sure if this is the only failing release since the test may short circuit after hitting this failure...I'm not sure.

**Comment by erickzhao** [comment]
Checking internally to fix the `headers/index.json` issue while developing a workaround for this problem at the level of this package. Thanks for the report!

**Comment by erickzhao** [comment]
We fixed this upstream last week!
