### ISSUE TITLE
collect script fails when trying to find new nightly release

### ISSUE THREAD

**Issue by ckerr** [electron/releases#37]
I found this while making a PR at https://github.com/electron/releases/pull/36

We build a map of version-to-tag this way:

```js
  const npmDistTaggedVersions = Object.keys(distTags)
    .reduce((acc, key) => {
      if (!key.match(/nightly/)) {
        if (!acc[distTags[key]]) {
          acc[distTags[key]] = [key]
        } else {
          acc[distTags[key]].push(key)
        }
      }
      return acc
    }, {})
  const latestNightly = npmElectronNightlyData.body['dist-tags'].latest
  npmDistTaggedVersions[latestNightly] = ['nightly']
```

Which currently yields

```
 { '4.0.4': [ 'latest', '4-0-x' ],
  '5.0.0-beta.2': [ 'beta', 'beta-5-0-x' ],
  '2.1.0-unsupported.20180809': [ 'unsupported' ],
  '1.8.8': [ '1-8-x' ],
  '1.7.16': [ '1-7-x' ],
  '3.0.15': [ '3-0-x' ],
  '2.0.17': [ '2-0-x' ],
  '4.0.0-beta.11': [ 'beta-4-0-x' ],
  '3.1.0-beta.5': [ 'beta-3-1-x' ],
  '3.1.3': [ '3-1-x' ],
  '6.0.0-nightly.20190123': [ 'nightly' ] }
```

The `releases` array holds these versions:

```
releases: 5.0.0-nightly.20190122
releases: 5.0.0-nightly.20190121
releases: 5.0.0-nightly.20190107
releases: 5.0.0-beta.2
releases: 5.0.0-beta.1
releases: 4.0.4
releases: 4.0.3
releases: 4.0.2
releases: 4.0.1
releases: 4.0.0
releases: 4.0.0-nightly.20181010
releases: 4.0.0-nightly.20181006
releases: 4.0.0-nightly.20180929
releases: 4.0.0-nightly.20180821
releases: 4.0.0-nightly.20180819
releases: 4.0.0-nightly.20180817
releases: 4.0.0-beta.11
releases: 4.0.0-beta.10
releases: 4.0.0-beta.9
releases: 4.0.0-beta.8
(older releases omitted)
```

So when we go to search for nightlies with this code:

```js
  const oldNightly = old.find(hasNpmDistTag('nightly')).version
  const newNightly = releases.find(hasNpmDistTag('nightly')).version
```

Since the only nightly tag is on `6.0.0-nightly.20190123` but that version isn't in `releases`, that second lin crashes when we try to assign `newNightly` by taking the `version` property of `undefined`.

**Comment by BinaryMuse** [comment]
I would say the root of the bug here is that `6.0.0-nightly.20190123` is the latest `nightly` tag on npm but isn't in the `releases` array. Indeed, neither `e/e` nor `e/nightlies` have this release. Do we know if there's a reason this is happening? Can you even install a nightly from npm without the corresponding release existing on GitHub?

**Comment by MarshallOfSound** [comment]
> Can you even install a nightly from npm without the corresponding release existing on GitHub?

No you can't

> Do we know if there's a reason this is happening?

Unknown, it should be impossible for a npm release to exist without a fully fledged github release.  My guess is a bad clean-up at some point or human intervention in the nightly release (might be mine or @codebytere )
