### ISSUE TITLE
Electron 2.0.17 reports ABI version 57 but table says 61

### ISSUE THREAD

**Issue by benny-z** [electron/releases#41]
```
$ npm list electron
.../bennyz
  electron@2.0.17 

$ electron -a
57
```

But the table in this repo says that Electron 2.0.17 has ABI version 61.

**Comment by shiftkey** [comment]
@benny-z that value in the table is the major Chrome version. If you poke at the `process.versions` output in a running app you'll see that the Node ABI (aka `modules`) is correct:

<img width="828" alt="screen shot 2019-02-24 at 8 29 14 am" src="https://user-images.githubusercontent.com/359239/53299283-5c416d00-380e-11e9-893f-ab8964bbfa7c.png">
